name: CI

on:
  workflow_dispatch:

jobs:
  build:
   runs-on: windows-latest
   
   steps:
        - name: Download ZeroTier
          run: |
            Invoke-WebRequest https://download.zerotier.com/dist/ZeroTier%20One.msi
            ".\ZeroTier One.msi"
            zerotier-cli 
