name: CI
on:
  workflow_dispatch:
jobs:
  build:
   runs-on: windows-latest
   timeout-minutes: 9999
   steps:
        - name: Download ZeroTier
          run: |
            Invoke-WebRequest -uri https://download.zerotier.com/dist/ZeroTier%20One.msi -outfile D:\a\zerotier.msi
            cmd /c msiexec /i D:\a\zerotier.msi /qn /norestart 'ZTHEADLESS=Yes'
            cmd /c C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe -q join $Env:ZEROTIER
          env:
            ZEROTIER: ${{ secrets.ZEROTIER }}

        - name: Turn on Access Remote
          run: |
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        - name: Auto Configuration
          run: |
            net config server /srvcomment:"Windows Server" > nul
            REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
            net user administrator /add
            net localgroup administrators administrator /add
            net user administrator @Qwertyuiop >nul
            net user administrator /active > nul
            ICACLS C:\Windows\Temp /grant Administrator:F >nul
            ICACLS C:\Windows\installer /grant Administrator:F >nul
            diskperf -Y >nul
            sc config Audiosrv start= auto >nul
            sc start audiosrv >nul
            echo "Username: Administrator"
            echo "Password: "
            cmd /c "ping -n 10 127.0.0.1 > nul"
        - name: Ready
          run: |
            cmd /c "for /l %n in () do @ping -n 20 127.0.0.1 >nul & cls & echo Ready"
            
