name: Lele
on:
  workflow_dispatch:
jobs:
  build:
   runs-on: windows-latest
   timeout-minutes: 9999
   steps:
      - name: Setup User Account
        run: |
            REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
            cmd /c "net user Administrator @RDPfree /add"
            cmd /c "net localgroup administrators Administrator /add"
            cmd /c "net user Administrator /active:yes"
            cmd /c "net user installer /delete"
            cmd /c "ICACLS C:\Windows\Temp /grant Administrator:F"
            cmd /c "ICACLS C:\Windows\Installer /grant Administrator:F"
            cmd /c "diskperf -y"
            cmd /c "sc config Audiosrv start= auto"
            cmd /c "sc start audiosrv"

      - name: Turn on Access Remote
        run: |
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Setup ZeroTier
        run: |
            Invoke-WebRequest -uri https://download.zerotier.com/dist/ZeroTier%20One.msi -outfile D:\a\zerotier.msi
            cmd /c msiexec /i D:\a\zerotier.msi /qn /norestart 'ZTHEADLESS=Yes'
            cmd /c C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe -q join $Env:ZEROTIER
        env:
            ZEROTIER: ${{ secrets.ZEROTIER }}
            
      - name: Your Remote Desktop is Already Running
        run: |
            $ipp = cmd /c C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe -q get $Env:ZEROTIER ip
            echo "IP      : $ipp"
            echo "Username: Administrator"
            echo "Password: @RDPfree"
            start-sleep -Seconds 5
        env:
            ZEROTIER: ${{ secrets.ZEROTIER }}
 
      - name: Ready
        run: |
          while($true){start-sleep -Seconds 10}
          
