name: Lele
on:
  workflow_dispatch:
jobs:
  build:
   runs-on: windows-latest
   timeout-minutes: 9999
   steps:
      - name: Setup User Account
        run: |
            REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
            cmd /c "net user Administrator @RDPfree /add"
            cmd /c "net localgroup administrators Administrator /add"
            cmd /c "net user Administrator /active:yes"
            cmd /c "net user installer /delete"
            cmd /c "ICACLS C:\Windows\Temp /grant Administrator:F"
            cmd /c "ICACLS C:\Windows\Installer /grant Administrator:F"
            cmd /c "diskperf -y"
            cmd /c "sc config Audiosrv start= auto"
            cmd /c "sc start audiosrv"

      - name: Turn on Access Remote
        run: |
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
            pwd

      - name: Setup APPS
        run: |
            pwd
            Invoke-WebRequest -uri "https://mirror2.internetdownloadmanager.com/idman642build20.exe?v=lt&filename=idman642build20.exe" -outfile $pwd\idm.exe
            .\idm.exe /skipdlgs
            echo IDM instalation complete
            Invoke-WebRequest -uri https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-701.exe -OutFile $pwd\winrar.exe
            .\winrar.exe /S
            echo Winrar instalation complete
            Invoke-WebRequest -UserAgent 'Wget' -Uri https://sourceforge.net/projects/qbittorrent/files/latest/download -OutFile $pwd\qBittorent.exe
            .\qBittorent.exe /S
            echo qBittorent instalation success
            
      - name: Setup ZeroTier
        run: |
            Invoke-WebRequest -uri https://download.zerotier.com/dist/ZeroTier%20One.msi -outfile D:\a\zerotier.msi
            echo "Download Success"
            cmd /c msiexec /i D:\a\zerotier.msi /qn /norestart 'ZTHEADLESS=Yes'
            echo "Installation Success"
            cmd /c C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe -q join $Env:ZEROTIER
            echo "Join network ID success"
        env:
            ZEROTIER: ${{ secrets.ZEROTIER }}
            
      - name: Your Remote Desktop is Already Running
        run: |
            echo "IP dibawah"
            C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe -q listnetworks
            echo "Username: Administrator"
            echo "Password: @RDPfree"
            start-sleep -Seconds 5
 
      - name: Ready
        run: |
          while($true){start-sleep -Seconds 10}
          
