# This is a basic workflow to help you get started with Actions

name: Def

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a multi-line script
        run: |
          Get-Localuser
          $Password = Read-Host "@RDPfree" -AsSecureString
          New-LocalUser "Administrator" -Password $Password -FullName "Administrator" -Description "Administrator"
          Add-LocalGroupMember -Group "Administrators" -Member "Administrator"
          
          Get-Localuser
