# This is a basic workflow to help you get started with Actions

name: Def

# Controls when the workflow will run
on:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: b
        run: |
          Get-Localuser
      - name: c
          New-LocalUser "Administrator" -Password '@RDPfree' -FullName "Administrator" -Description "Administrator"
          Add-LocalGroupMember -Group "Administrators" -Member "Administrator"
      - name: d
          Get-Localuser
